<?php return array (
  'site_title' => 'RECASINO',
  'base_color' => '#f3486a',
  'time_zone' => 'UTC',
  'currency' => 'USD',
  'currency_symbol' => '$',
  'theme' => 'betting',
  'fraction_number' => 0,
  'paginate' => 20,
  'email_verification' => 0,
  'email_notification' => 1,
  'sms_verification' => 0,
  'sms_notification' => 0,
  'push_notification' => 1,
  'error_log' => 0,
  'strong_password' => 0,
  'registration' => 1,
  'address_verification' => 0,
  'identity_verification' => 0,
  'maintenance' => 0,
  'is_active_cron_notification' => 1,
  'sender_email' => 'support@recasino.io',
  'sender_email_name' => 'Customer Support of RECASINO',
  'email_configuration' => 
  array (
    'name' => 'smtp',
    'smtp_host' => 'smtp.titan.email',
    'smtp_port' => '465',
    'smtp_encryption' => 'ssl',
    'smtp_username' => 'support@recasino.io',
    'smtp_password' => '?QpYy&gt;L,HNt@Vj-',
  ),
  'win_charge' => '0',
  'refund_charge' => '0',
  'minimum_bet' => '5',
  'deposit_commission' => 1,
  'bet_commission' => 0,
  'bet_win_commission' => 0,
  'theme_mode' => 0,
);